apiVersion: v1
kind: Service
metadata:
        name: problembank-server
spec:
        sessionAffinity: ClientIP
        type: LoadBalancer
        externalIPs:
                - 210.94.194.102
        selector:
                app: problembank-server
        ports:
                - protocol: TCP
                  port: 3003
                  targetPort: 3003
---
apiVersion: apps/v1
kind: Deployment
metadata:
        labels:
                app: problembank-server
        name: problembank-server
spec:
        replicas: 5
        selector:
                matchLabels:
                        app: problembank-server
        template:
                metadata:
                        labels:
                                app: problembank-server
                spec:
                        affinity:
                                podAntiAffinity:
                                        requiredDuringSchedulingIgnoredDuringExecution:
                                        - labelSelector:
                                                  matchExpressions:
                                                  - key: app
                                                    operator: In
                                                    values: 
                                                    - problembank-server
                                          topologyKey: "kubernetes.io/hostname"
                        containers:
                                - image: dguplms/problembank-server:11.1
                                  name: problembank-server
                                  ports:
                                        - containerPort: 3003
                                  imagePullPolicy: Always
                        restartPolicy: Always
