apiVersion: v1
kind: Service
metadata:
        name: problembank-score-server
spec:
        sessionAffinity: ClientIP
        type: LoadBalancer
        externalIPs: 
                - 210.94.194.102
        selector:
                app: problembank-score-server
        ports:
                - protocol: TCP
                  port: 5111
                  targetPort: 3005
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-banks
  labels:
    name: nfs-pv-banks
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/RAID-1/PROJECTS/bank_problem
    server: 210.94.194.102
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-pvc-banks
spec:
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      name: nfs-pv-banks
---
apiVersion: apps/v1
kind: Deployment
metadata:
        labels: 
            app: problembank-score-server
        name: problembank-score-server
spec:
        replicas: 5
        selector: 
          matchLabels: 
            app: problembank-score-server
        template:
            metadata:
              labels:
                app: problembank-score-server
            spec: 
              affinity:
                podAntiAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                  - labelSelector:
                      matchExpressions:
                      - key: app
                        operator: In
                        values: 
                        - problembank-score-server
                    topologyKey: "kubernetes.io/hostname"
              containers:
                - image: dguplms/problembank-score-server:11.1
                  name: problembank-score-server
                  ports:
                      - containerPort: 3005
                  volumeMounts:
                      - name: pvc-volume-banks
                        mountPath: /home/plass/problem-score-server/DEBUG_TEMP_PATH_BANK_PROBLEMS/
                  imagePullPolicy: Always
              volumes:
                - name: pvc-volume-banks
                  persistentVolumeClaim:
                    claimName: nfs-pvc-banks
              restartPolicy: Always    
            
