apiVersion: v1
kind: Service
metadata:
        name: project-client
spec:
        sessionAffinity: ClientIP
        type: LoadBalancer
        externalIPs:
                - 210.94.194.102
        selector:
                app: project-client
        ports:
                - name: http
                  protocol: TCP
                  port: 5110
                  targetPort: 5110
---
apiVersion: apps/v1
kind: Deployment
metadata:
        labels:
                app: project-client
        name: project-client
spec:
        replicas: 5
        selector:
                matchLabels:
                        app: project-client
        template:
                metadata:
                        labels:
                                app: project-client
                spec:
                        containers:
                                - image: dguplms/project-client:1.3
                                  imagePullPolicy: Always
                                  name: project-client
                                  ports:
                                        - containerPort: 5110
                        restartPolicy: Always
