apiVersion: v1
kind: Service
metadata:
        name: server-down
spec:
        sessionAffinity: ClientIP
        selector:
                app: server-down
        ports:
                - name: http
                  port: 5113
                  targetPort: 5113                
---
apiVersion: apps/v1
kind: Deployment
metadata:
        labels:
                app: server-down
        name: server-down
spec:
        selector:
                matchLabels:
                        app: server-down
        template:
                metadata:
                        labels:
                                app: server-down
                spec:
                        containers:
                                - image: dguplms/serverdown:1.0
                                  imagePullPolicy: Always
                                  name: server-down
                                  ports:
                                        - containerPort: 5113
                        restartPolicy: Always
